[project]
name = "advent-of-code"
version = "0.1.0"
description = "Python solutions for the Advent of Code challenges."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
]
